#==========================================
# 1. SERVER & PROJECT CONFIG (Phase 1)
# ==========================================
spring.application.name=hpms
server.port=8788

# ==========================================
# 2. DATABASE & LIQUIBASE (Phase 1 & 2)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.properties.hibernate.default_schema=hpms-db
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION}

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# =========================
# GEMINI (CHAT)
# =========================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.enabled=true
spring.ai.google.genai.embedding.enabled=false

# =========================
# 3. TRANSFORMERS (LOCAL EMBEDDING)
# =========================
spring.ai.embedding.transformer.enabled=true

# =========================
# 4. PGVECTOR (384 Dimensions)
# =========================
spring.ai.vectorstore.pgvector.jdbc.initialize-schema=false
spring.ai.vectorstore.pgvector.jdbc.table-name=vector_store
spring.ai.vectorstore.pgvector.jdbc.dimensions=384
spring.ai.vectorstore.pgvector.jdbc.distance-type=COSINE_DISTANCE