package com.l2p.hmps.model;

public enum EventType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_CANCELLED,

    LAB_RESULT_SUBMITTED,
    LAB_RESULT_CRITICAL,
    LAB_RESULT_VERIFIED,

    BILL_GENERATED,
    BILL_PARTIALLY_PAID,
    BILL_PAID,

    PRESCRIPTION_CREATED,
    PRESCRIPTION_FILLED
}
